runtime: python27
api_version: 1
threadsafe: true
application: udacity-user-registration

libraries:
  - name: jinja2
    version: latest
  - name: webapp2
    version: latest

handlers:
  - url: /.*
    script: registration.app
